version: "3"

services:
    db:
        image: redis
        restart: always
        command: --appendonly yes
        ports:
            - "6399:6379"
        volumes:
            - ./redis-data:/data

    main:
        build: .
        command: python run.py
        volumes:
            - .:/code
        ports:
            - "5000:5000"
        links:
            - db